import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class CountriesService {

  constructor() { }

  getCountries(){
 return [{
  "id": "1",
  "country": "Afghanistan",
  "capital": "Kabul",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "Afghani (AFN)",

},
{
  "id": "2",
  "country": "Albania",
  "capital": "Tirana",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "Albania lek(ALL)",

},
{
  "id": "3",
  "country": "Algeria",
  "capital": "Alger",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "Algerian dinar",

},
{
  "id": "4",
  "country": "American Samoa",
  "capital": "Fagatogo",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "United States dollar (USD)",

},
{
  "id": "5",
  "country": "Andorra",
  "capital": "Andorra la Vella",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "European dollar",

},
{
  "id": "6",
  "country": "Angola",
  "capital": "Luanda",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "Angolan Kwanza (AOA)",

},
{
  "id": "7",
  "country": "Anguilla",
  "capital": "The Valley",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "8",
  "country": "Antarctica",
  "capital": null,
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "9",
  "country": "Antigua and Barbuda",
  "capital": "Saint John's",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "10",
  "country": "Argentina",
  "capital": "Buenos Aires",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "11",
  "country": "Armenia",
  "capital": "Yerevan",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "12",
  "country": "Aruba",
  "capital": "Oranjestad",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{

  "id": "13",
  "country": "Australia",
  "capital": "Canberra",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "14",
  "country": "Austria",
  "capital": "Wien",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "15",
  "country": "Azerbaijan",
  "capital": "Baku",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "16",
  "country": "Bahamas",
  "capital": "Nassau",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "17",
  "country": "Bahrain",
  "capital": "al-Manama",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "18",
  "country": "Bangladesh",
  "capital": "Dhaka",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "19",
  "country": "Barbados",
  "capital": "Bridgetown",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",
},

{
  "id": "20",
  "country": "Belarus",
  "capital": "Minsk",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "21",
  "country": "Belgium",
  "capital": "Bruxelles [Brussel]",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "22",
  "country": "Belize",
  "capital": "Belmopan",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "23",
  "country": "Benin",
  "capital": "Porto-Novo",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "24",
  "country": "Bermuda",
  "capital": "Hamilton",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "25",
  "country": "Bhutan",
  "capital": "Thimphu",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "26",
  "country": "Bolivia",
  "capital": "La Paz",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "27",
  "country": "Bosnia and Herzegovina",
  "capital": "Sarajevo",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "28",
  "country": "Botswana",
  "capital": "Gaborone",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "29",
  "country": "Bouvet Island",
  "capital": null,
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "30",
  "country": "Brazil",
  "capital": "Brasília",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "31",
  "country": "British Indian Ocean Territory",
  "capital": null,
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "32",
  "country": "Brunei",
  "capital": "Bandar Seri Begawan",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "33",
  "country": "Bulgaria",
  "capital": "Sofia",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "34",
  "country": "Burkina Faso",
  "capital": "Ouagadougou",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "35",
  "country": "Burundi",
  "capital": "Bujumbura",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "36",
  "country": "Cambodia",
  "capital": "Phnom Penh",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "37",
  "country": "Cameroon",
  "capital": "Yaound",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "38",
  "country": "Canada",
  "capital": "Ottawa",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "39",
  "country": "Cape Verde",
  "capital": "Praia",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "40",
  "country": "Cayman Islands",
  "capital": "George Town",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "41",
  "country": "Central African Republic",
  "capital": "Bangui",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "42",
  "country": "Chad",
  "capital": "N'Djam",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "43",
  "country": "Chile",
  "capital": "Santiago de Chile",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "44",
  "country": "China",
  "capital": "Peking",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "45",
  "country": "Christmas Island",
  "capital": "Flying Fish Cove",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "46",
  "country": "Cocos (Keeling) Islands",
  "capital": "West Island",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "47",
  "country": "Colombia",
  "capital": "Santaf",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "48",
  "country": "Comoros",
  "capital": "Moroni",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "49",
  "country": "Congo",
  "capital": "Brazzaville",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "50",
  "country": "Cook Islands",
  "capital": "Avarua",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "51",
  "country": "Costa Rica",
  "capital": "San Jos",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "52",
  "country": "Croatia",
  "capital": "Zagreb",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "53",
  "country": "Cuba",
  "capital": "La Habana",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "54",
  "country": "Cyprus",
  "capital": "Nicosia",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "55",
  "country": "Czech Republic",
  "capital": "Praha",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "56",
  "country": "Denmark",
  "capital": "Copenhagen",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "57",
  "country": "Djibouti",
  "capital": "Djibouti",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "58",
  "country": "Dominica",
  "capital": "Roseau",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "59",
  "country": "Dominican Republic",
  "capital": "Santo Domingo de Guzm",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "60",
  "country": "East Timor",
  "capital": "Dili",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "61",
  "country": "Ecuador",
  "capital": "Quito",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "62",
  "country": "Egypt",
  "capital": "Cairo",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "63",
  "country": "El Salvador",
  "capital": "San Salvador",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "64",
  "country": "England",
  "capital": "London",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "65",
  "country": "Equatorial Guinea",
  "capital": "Malabo",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "66",
  "country": "Eritrea",
  "capital": "Asmara",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "67",
  "country": "Estonia",
  "capital": "Tallinn",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "68",
  "country": "Ethiopia",
  "capital": "Addis Abeba",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "69",
  "country": "Falkland Islands",
  "capital": "Stanley",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "70",
  "country": "Faroe Islands",
  "capital": "Tórshavn",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "71",
  "country": "Fiji Islands",
  "capital": "Suva",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "72",
  "country": "Finland",
  "capital": "Helsinki [Helsingfors]",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "73",
  "country": "France",
  "capital": "Paris",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "74",
  "country": "French Guiana",
  "capital": "Cayenne",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "75",
  "country": "French Polynesia",
  "capital": "Papeete",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "76",
  "country": "French Southern territories",
  "capital": null,
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "77",
  "country": "Gabon",
  "capital": "Libreville",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "78",
  "country": "Gambia",
  "capital": "Banjul",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "79",
  "country": "Georgia",
  "capital": "Tbilisi",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "80",
  "country": "Germany",
  "capital": "Berlin",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "81",
  "country": "Ghana",
  "capital": "Accra",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "82",
  "country": "Gibraltar",
  "capital": "Gibraltar",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "83",
  "country": "Greece",
  "capital": "Athenai",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{

  "id": "84",
  "country": "Greenland",
  "capital": "Nuuk",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "85",
  "country": "Grenada",
  "capital": "Saint George's",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "86",
  "country": "Guadeloupe",
  "capital": "Basse-Terre",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "87",
  "country": "Guam",
  "capital": "Aga",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "88",
  "country": "Guatemala",
  "capital": "Ciudad de Guatemala",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "89",
  "country": "Guinea",
  "capital": "Conakry",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "90",
  "country": "Guinea-Bissau",
  "capital": "Bissau",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "91",
  "country": "Guyana",
  "capital": "Georgetown",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "92",
  "country": "Haiti",
  "capital": "Port-au-Prince",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "93",
  "country": "Heard Island and McDonald Islands",
  "capital": null,
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "94",
  "country": "Holy See (Vatican capital State)",
  "capital": "Citt",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "95",
  "country": "Honduras",
  "capital": "Tegucigalpa",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "96",
  "country": "Hong Kong",
  "capital": "Victoria",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "97",
  "country": "Hungary",
  "capital": "Budapest",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "98",
  "country": "Iceland",
  "capital": "Reykjav",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "99",
  "country": "India",
  "capital": "New Delhi",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "100",
  "country": "Indonesia",
  "capital": "Jakarta",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{

  "id": "101",
  "country": "Iran",
  "capital": "Tehran",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "102",
  "country": "Iraq",
  "capital": "Baghdad",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "103",
  "country": "Ireland",
  "capital": "Dublin",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "104",
  "country": "Israel",
  "capital": "Jerusalem",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "105",
  "country": "Italy",
  "capital": "Roma",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "106",
  "country": "Ivory Coast",
  "capital": "Yamoussoukro",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "107",
  "country": "Jamaica",
  "capital": "Kingston",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "108",
  "country": "Japan",
  "capital": "Tokyo",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{

  "id": "109",
  "country": "Jordan",
  "capital": "Amman",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "110",
  "country": "Kazakhstan",
  "capital": "Astana",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "111",
  "country": "Kenya",
  "capital": "Nairobi",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "112",
  "country": "Kiribati",
  "capital": "Bairiki",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "113",
  "country": "Kuwait",
  "capital": "Kuwait",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "114",
  "country": "Kyrgyzstan",
  "capital": "Bishkek",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "115",
  "country": "Laos",
  "capital": "Vientiane",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "116",
  "country": "Latvia",
  "capital": "Riga",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "117",
  "country": "Lebanon",
  "capital": "Beirut",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "118",
  "country": "Lesotho",
  "capital": "Maseru",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "119",
  "country": "Liberia",
  "capital": "Monrovia",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "120",
  "country": "Libyan Arab Jamahiriya",
  "capital": "Tripoli",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "121",
  "country": "Liechtenstein",
  "capital": "Vaduz",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "122",
  "country": "Lithuania",
  "capital": "Vilnius",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "123",
  "country": "Luxembourg",
  "capital": "Luxembourg [Luxemburg/L",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "124",
  "country": "Macao",
  "capital": "Macao",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "125",
  "country": "North Macedonia",
  "capital": "Skopje",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "126",
  "country": "Madagascar",
  "capital": "Antananarivo",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "127",
  "country": "Malawi",
  "capital": "Lilongwe",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "128",
  "country": "Malaysia",
  "capital": "Kuala Lumpur",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "129",
  "country": "Maldives",
  "capital": "Male",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "130",
  "country": "Mali",
  "capital": "Bamako",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "131",
  "country": "Malta",
  "capital": "Valletta",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "132",
  "country": "Marshall Islands",
  "capital": "Dalap-Uliga-Darrit",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "133",
  "country": "Martinique",
  "capital": "Fort-de-France",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "134",
  "country": "Mauritania",
  "capital": "Nouakchott",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "135",
  "country": "Mauritius",
  "capital": "Port-Louis",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "136",
  "country": "Mayotte",
  "capital": "Mamoutzou",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "137",
  "country": "Mexico",
  "capital": "Ciudad de M",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "138",
  "country": "Micronesia, Federated States of",
  "capital": "Palikir",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "139",
  "country": "Moldova",
  "capital": "Chisinau",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "140",
  "country": "Monaco",
  "capital": "Monaco-Ville",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "141",
  "country": "Mongolia",
  "capital": "Ulan Bator",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{

  "id": "142",
  "country": "Montenegro",
  "capital": "Podgorica",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "143",
  "country": "Montserrat",
  "capital": "Plymouth",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{

  "id": "144",
  "country": "Morocco",
  "capital": "Rabat",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "145",
  "country": "Mozambique",
  "capital": "Maputo",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "146",
  "country": "Myanmar",
  "capital": "Rangoon (Yangon)",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "147",
  "country": "Namibia",
  "capital": "Windhoek",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "148",
  "country": "Nauru",
  "capital": "Yaren",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "149",
  "country": "Nepal",
  "capital": "Kathmandu",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "150",
  "country": "Netherlands",
  "capital": "Amsterdam",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "151",
  "country": "Netherlands Antilles",
  "capital": "Willemstad",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "152",
  "country": "New Caledonia",
  "capital": "Noum",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "153",
  "country": "New Zealand",
  "capital": "Wellington",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "154",
  "country": "Nicaragua",
  "capital": "Managua",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "155",
  "country": "Niger",
  "capital": "Niamey",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "156",
  "country": "Nigeria",
  "capital": "Abuja",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "157",
  "country": "Niue",
  "capital": "Alofi",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "158",
  "country": "Norfolk Island",
  "capital": "Kingston",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "159",
  "country": "North Korea",
  "capital": "Pyongyang",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "160",
  "country": "Northern Ireland",
  "capital": "Belfast",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "161",
  "country": "Northern Mariana Islands",
  "capital": "Garapan",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{

  "id": "162",
  "country": "Norway",
  "capital": "Oslo",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "163",
  "country": "Oman",
  "capital": "Masqat",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "164",
  "country": "Pakistan",
  "capital": "Islamabad",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "165",
  "country": "Palau",
  "capital": "Koror",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "166",
  "country": "Palestine",
  "capital": "Gaza",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "167",
  "country": "Panama",
  "capital": "Ciudad de Panam",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "168",
  "country": "Papua New Guinea",
  "capital": "Port Moresby",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "169",
  "country": "Paraguay",
  "capital": "Asunci",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "170",
  "country": "Peru",
  "capital": "Lima",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "171",
  "country": "Philippines",
  "capital": "Manila",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "172",
  "country": "Pitcairn",
  "capital": "Adamstown",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "173",
  "country": "Poland",
  "capital": "Warszawa",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "174",
  "country": "Portugal",
  "capital": "Lisboa",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "175",
  "country": "Puerto Rico",
  "capital": "San Juan",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "176",
  "country": "Qatar",
  "capital": "Doha",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "177",
  "country": "Reunion",
  "capital": "Saint-Denis",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "178",
  "country": "Romania",
  "capital": "Bucuresti",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "179",
  "country": "Russian Federation",
  "capital": "Moscow",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "180",
  "country": "Rwanda",
  "capital": "Kigali",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "181",
  "country": "Saint Helena",
  "capital": "Jamestown",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "182",
  "country": "Saint Kitts and Nevis",
  "capital": "Basseterre",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "183",
  "country": "Saint Lucia",
  "capital": "Castries",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "184",
  "country": "Saint Pierre and Miquelon",
  "capital": "Saint-Pierre",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "185",
  "country": "Saint Vincent and the Grenadines",
  "capital": "Kingstown",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "186",
  "country": "Samoa",
  "capital": "Apia",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "187",
  "country": "San Marino",
  "capital": "San Marino",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "188",
  "country": "Sao Tome and Principe",
  "capital": "S",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "189",
  "country": "Saudi Arabia",
  "capital": "Riyadh",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "190",
  "country": "Scotland",
  "capital": "Edinburgh",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "191",
  "country": "Senegal",
  "capital": "Dakar",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "192",
  "country": "Seychelles",
  "capital": "Victoria",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "193",
  "country": "Sierra Leone",
  "capital": "Freetown",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "194",
  "country": "Singapore",
  "capital": "Singapore",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "195",
  "country": "Slovakia",
  "capital": "Bratislava",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "196",
  "country": "Slovenia",
  "capital": "Ljubljana",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "197",
  "country": "Solomon Islands",
  "capital": "Honiara",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "198",
  "country": "Somalia",
  "capital": "Mogadishu",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "199",
  "country": "South Africa",
  "capital": "Pretoria",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "200",
  "country": "South Georgia and the South Sandwich Islands",
  "capital": null,
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "200",
  "country": "South Korea",
  "capital": "Seoul",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "201",
  "country": "South Sudan",
  "capital": "Juba",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "202",
  "country": "Spain",
  "capital": "Madrid",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",
},
{
  "id": "203",
  "country": "SriLanka",
  "capital": null,
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "204",
  "country": "Sudan",
  "capital": "Khartum",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "205",
  "country": "Suriname",
  "capital": "Paramaribo",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "206",
  "country": "Svalbard and Jan Mayen",
  "capital": "Longyearbyen",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "207",
  "country": "Swaziland",
  "capital": "Mbabane",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "208",
  "country": "Sweden",
  "capital": "Stockholm",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "209",
  "country": "Switzerland",
  "capital": "Bern",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "210",
  "country": "Syria",
  "capital": "Damascus",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "211",
  "country": "Tajikistan",
  "capital": "Dushanbe",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "212",
  "country": "Tanzania",
  "capital": "Dodoma",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "213",
  "country": "Thailand",
  "capital": "Bangkok",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "214",
  "country": "The Democratic Republic of Congo",
  "capital": null,
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "215",
  "country": "Togo",
  "capital": "Lom",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "216",
  "country": "Tokelau",
  "capital": "Fakaofo",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "217",
  "country": "Tonga",
  "capital": "Nuku'alofa",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "218",
  "country": "Trinidad and Tobago",
  "capital": "Port-of-Spain",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",
},
{
  "id": "219",
  "country": "Tunisia",
  "capital": "Tunis",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "220",
  "country": "Turkey",
  "capital": "Ankara",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "121",
  "country": "Turkmenistan",
  "capital": "Ashgabat",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "222",
  "country": "Turks and Caicos Islands",
  "capital": "Cockburn Town",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "223",
  "country": "Tuvalu",
  "capital": "Funafuti",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "225",
  "country": "Uganda",
  "capital": "Kampala",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "226",
  "country": "Ukraine",
  "capital": "Kyiv",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "227",
  "country": "United Arab Emirates",
  "capital": "Abu Dhabi",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "228",
  "country": "United Kingdom",
  "capital": "London",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "229",
  "country": "United States",
  "capital": "Washington",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "230",
  "country": "United States Minor Outlying Islands",
  "capital": null,
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "131",
  "country": "Uruguay",
  "capital": "Montevideo",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",
},
{
  "id": "232",
  "country": "Uzbekistan",
  "capital": "Toskent",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "233",
  "country": "Vanuatu",
  "capital": "Port-Vila",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "234",
  "country": "Venezuela",
  "capital": "Caracas",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "235",
  "country": "Vietnam",
  "capital": "Hanoi",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "236",
  "country": "Virgin Islands, British",
  "capital": "Road Town",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "237",
  "country": "Virgin Islands, U.S.",
  "capital": "Charlotte Amalie",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "238",
  "country": "Wales",
  "capital": "Cardiff",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "239",
  "country": "Wallis and Futuna",
  "capital": "Mata-Utu",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "240",
  "country": "Western Sahara",
  "capital": "El-Aai",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "141",
  "country": "Yemen",
  "capital": "Sanaa",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "242",
  "country": "Yugoslavia",
  "capital": "Beograd",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "243",
  "country": "Zambia",
  "capital": "Lusaka",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

},
{
  "id": "244",
  "country": "Zimbabwe",
  "capital": "Harare",
  "domain": "domainVal",
  "language": "languageVal",
  "continent": "continentVal",
  "area": "areaVal",
  "population": "populationVal",
  "callingCode": "callingCodeVal",
  "density": "densityVal",
  "imgUrl": "imgUrlVal",
  "currency": "newvalue",

}
]
}

}

// Test


// {'id':1 , 'city':'Angular' , 'detail':'Presented by google' },
// {'id':2 , 'city':'Bootstrap', 'detail':'Very famous css framework'},
// {'id':3 , 'city':'Vue', 'detail':'Light weight js framework'},
// {'id':4 , 'city':'React', 'detail': 'Framework by facebook'},
// {'id':5 , 'city':'AntDesign', 'detail':'Design for the developer'},
// {'id':6 , 'city':'Ionic', 'detail':'Make apps for the multi platform application'}
